### ISSUE TITLE
private links

### ISSUE THREAD

**Issue by Behrooz-Amoozad** [dotamatch/dotamatch#10]
formatter.js, after line 99 (match.players[u].player_name = "*private*";) player should be marked as private and no dotabuff link to 4294967295 should be generated for him. or maybe just the user_id as a flag when generating the link?

**Comment by dodekeract** [comment]
But then again: what if that user decides to join dotabuff? His match will then appear in the history.

**Comment by Behrooz-Amoozad** [comment]
Thanks for replying. the links point to https://www.dotabuff.com/players/4294967295. there are 2 cases here:
1. we update the posts later, then this shouldn't be a problem.
2. we don't update the posts later, then we have dead links.

either way, this behavior leads to deadlinks; temporarily or permanently.

**Comment by dotamatch** [comment]
Should be fixed now, thanks
