### ISSUE TITLE
Add date and time of match.

### ISSUE THREAD

**Issue by vasia123** [dotamatch/dotamatch#4]
This would really helpfull. ( idea from http://www.reddit.com/r/DotA2/comments/30js9a/new_drop_system_someone_got_2_arcanas_after_one/#form-t1_cptdec9736 )

**Comment by dotamatch** [comment]
I'll look into it today!

**Comment by dotamatch** [comment]
Done :+1:

**Comment by vasia123** [comment]
Good job!)
