### ISSUE TITLE
Double the comments, double the karma.

### ISSUE THREAD

**Issue by dodekeract** [dotamatch/dotamatch#9]
The bot seems to have a rare bug. It double-commented on [this particular comment](https://www.reddit.com/r/DotA2/comments/470o28/stop_cheating_its_really_obvious/d09jlnc).

**Comment by dotamatch** [comment]
Was running two instances of the bot on my server. My bad!

**Comment by dodekeract** [comment]
Glad to hear that it was a simple fix, most of the time this kind of issue is quite complicated to trace down. :smile:
